import{a as S,S as w,i as M}from"./assets/vendor-F1LeQrrD.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function y(t,a=1){return(await S.get("https://pixabay.com/api/",{params:{key:"54610826-258ca21fce67e24d1b909df87",per_page:15,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a}})).data}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-load-more")};function f(t){const a=t.map(({webformatURL:r,comments:i,downloads:e,likes:o,largeImageURL:c,tags:L,views:b})=>`<li class="gallery-item">
            <a class="gallery-link" href="${c}">
            <img src="${r}" alt="${L}">
            </a>
        <ul class="description-list">
            <li class="description-item">comments ${i}</li>
            <li class="description-item">downloads ${e}</li>
            <li class="description-item">likes ${o}</li>
            <li class="description-item">views ${b}</li>
        </ul>
        </li>`).join("");s.gallery.insertAdjacentHTML("beforeend",a),q.refresh()}let q=new w(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function P(){s.gallery.innerHTML=""}function n(t){M.error({position:"topRight",title:"Error",message:t})}function m(){s.loader.classList.remove("hidden")}function h(){s.loader.classList.add("hidden")}function g(){s.btnLoadMore.classList.remove("hidden")}function u(){s.btnLoadMore.classList.add("hidden")}let l=1;const p=15;let d="";s.form.addEventListener("submit",$);s.btnLoadMore.addEventListener("click",v);async function $(t){t.preventDefault();const a=t.target.elements["search-text"].value.trim();if(!a)return n("Невалидный ввод");a!==d&&(l=1,P()),d=a,u(),m();try{const r=await y(d,l);if(r.hits.length===0)return n("Sorry, there are no images matching your search query. Please try again!");f(r.hits);const i=Math.ceil(r.totalHits/p);l<i?g():(n("Sorry, thats all for your search."),u())}catch(r){n(`${r} Sorry, there are no images matching your search query. Please try again!`)}finally{h(),t.target.reset()}}async function v(){l++,u(),m();try{const t=await y(d,l);f(t.hits);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log(r),window.scrollBy({left:0,top:r*2,behavior:"smooth"});const i=Math.ceil(t.totalHits/p);l<i?g():(u(),n("Sorry, thats all for your search."))}catch(t){n(`${t} Sorry, there are no images matching your search query. Please try again!`)}finally{h()}}
//# sourceMappingURL=index.js.map
