import{a as S,S as w,i as M}from"./assets/vendor-F1LeQrrD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function y(t,r=1){return(await S.get("https://pixabay.com/api/",{params:{key:"54610826-258ca21fce67e24d1b909df87",per_page:15,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r}})).data}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-load-more")};function f(t){const r=t.map(({webformatURL:a,comments:i,downloads:e,likes:o,largeImageURL:c,tags:L,views:b})=>`<li class="gallery-item">
            <a class="gallery-link" href="${c}">
            <img src="${a}" alt="${L}">
            </a>
        <ul class="description-list">
            <li class="description-item">comments ${i}</li>
            <li class="description-item">downloads ${e}</li>
            <li class="description-item">likes ${o}</li>
            <li class="description-item">views ${b}</li>
        </ul>
        </li>`).join("");s.gallery.insertAdjacentHTML("beforeend",r),q.refresh()}let q=new w(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function P(){s.gallery.innerHTML=""}function n(t){M.error({position:"topRight",title:"Error",message:t})}function m(){s.loader.classList.remove("hidden")}function h(){s.loader.classList.add("hidden")}function g(){s.btnLoadMore.classList.remove("hidden")}function d(){s.btnLoadMore.classList.add("hidden")}let l=1;const p=15;let u="";s.form.addEventListener("submit",$);s.btnLoadMore.addEventListener("click",v);async function $(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r)return n("Невалидный ввод");l=1,P(),u=r,d(),m();try{const a=await y(u,l);if(a.hits.length===0)return n("Sorry, there are no images matching your search query. Please try again!");f(a.hits);const i=Math.ceil(a.totalHits/p);l<i?g():(n("Sorry, thats all for your search."),d())}catch(a){n(`${a} Sorry, there are no images matching your search query. Please try again!`)}finally{h(),t.target.reset()}}async function v(){l++,d(),m();try{const t=await y(u,l);f(t.hits);const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;console.log(i),window.scrollBy({left:0,top:i*2,behavior:"smooth"})}const a=Math.ceil(t.totalHits/p);l<a?g():(d(),n("Sorry, thats all for your search."))}catch(t){n(`${t} Sorry, there are no images matching your search query. Please try again!`)}finally{h()}}
//# sourceMappingURL=index.js.map
