import{a as b,S,i as q}from"./assets/vendor-F1LeQrrD.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function f(t,i=1){return(await b.get("https://pixabay.com/api/",{params:{key:"54610826-258ca21fce67e24d1b909df87",per_page:15,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i}})).data}const a={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-load-more")};function m(t){const i=t.map(({comments:o,downloads:s,likes:e,largeImageURL:r,tags:l,views:g,previewURL:L})=>`<li class="gallery-item">
            <a class="gallery-link" href="${r}">
            <img src="${L}" alt="${l}">
            </a>
        <ul class="description-list">
            <li class="description-item">comments ${o}</li>
            <li class="description-item">downloads ${s}</li>
            <li class="description-item">likes ${e}</li>
            <li class="description-item">views ${g}</li>
        </ul>
        </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",i),w.refresh()}let w=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function M(){a.gallery.innerHTML=""}function d(t){q.error({position:"topRight",title:"Error",message:t})}function y(){a.loader.classList.remove("hidden")}function p(){a.loader.classList.add("hidden")}function h(){a.btnLoadMore.classList.remove("hidden")}function u(){a.btnLoadMore.classList.add("hidden")}let n=1,c="";a.form.addEventListener("submit",$);function $(t){t.preventDefault();const i=t.target.elements["search-text"].value.trim();if(y(),!!i){if(i!==c&&(n=1,M()),c=i,c==="")return d("Невалидный ввод");if(u(),n>=33){u();return}f(c,n).then(o=>{if(o.hits.length===0)return d("Sorry, there are no images matching your search query. Please try again!");o.hits.length>0&&h(),m(o.hits)}).catch(o=>d(`${o}Sorry, there are no images matching your search query. Please try again!`)).finally(()=>{p(),t.target.reset()})}}a.btnLoadMore.addEventListener("click",async()=>{if(n++,n>=33){u();return}u(),y();try{const t=await f(c,n);m(t.hits)}catch(t){d(`${t}Sorry, there are no images matching your search query. Please try again!`)}finally{p(),h()}});
//# sourceMappingURL=index.js.map
